version: '3.8'

services:
  app:
    build: .
    ports:
      - "8006:8006"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      # Map the container's MongoDB port to host port 27020.
      - "27020:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
