services:
  mongodb:
    image: mongo:${MONGO_VERSION}
    container_name: crocodile_mongodb
    ports:
      - "${MONGO_SERVER_PORT}:27017"
    volumes:
      - ./mongo_data:/data/db  # Local directory for MongoDB data
      - ./mongod.conf:/etc/mongod.conf  # Custom MongoDB config
    command: mongod --config /etc/mongod.conf

  fastapi:
    build:
      context: .  # Path to the FastAPI backend
      dockerfile: backend/Dockerfile  # Use the Dockerfile in the backend folder
    container_name: crocodile_fastapi
    ports:
      - "${FASTAPI_SERVER_PORT:-8000}:8000"  # Default to 8000 if not set
    volumes:
    # Mount the app directory to the container
      - ./backend/app:/app
      - ./crocodile:/app/crocodile
      - ./backend/scripts:/app/scripts
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env  # Load environment variables from .env file

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: crocodile_elastic
    volumes:
      - ./elasticdata:/usr/share/elasticsearch/data
    ports:
      - "${ELASTIC_PORT:-9200}:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.authc.api_key.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: crocodile_kibana
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
